(() => {
'use strict';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)],G=window.SamiGeometry,LS_KEY='sami.project.v1';
const copy=G.copy,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>window.crypto?.randomUUID?.()||'sami-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const SERVICES={electric:{name:'Underground electricity',color:'#df4141'},gas:{name:'Gas',color:'#ce9b00'},water:{name:'Water',color:'#1481d4'},drainage:{name:'Waste / drainage',color:'#826648'},telecom:{name:'Telecoms',color:'#bd661d'},ohl:{name:'Overhead lines',color:'#c3429e'},ecology:{name:'Ecology / habitat',color:'#32965d',area:true},sssi:{name:'SSSI',color:'#428a47',area:true},tpo:{name:'Tree protection',color:'#227c6d',area:true},heritage:{name:'Listed / heritage',color:'#9659a3',area:true},archaeology:{name:'Archaeology',color:'#b96c50',area:true},other:{name:'Other restriction / permit',color:'#697eb6',area:true}};
const PRODUCTS={lion:{name:'Lion Panel',length:3,width:2.41,overlap:0,lateralOverlap:0,color:'#b19b39'},hybrid:{name:'Hybrid Panel',length:3,width:2.44,overlap:0,lateralOverlap:0,color:'#ac7d31'},tuff:{name:'TuffTrak',length:3,width:2.5,overlap:0,lateralOverlap:0,color:'#328ba3'},sabre:{name:'Sabre-X',length:4,width:2,overlap:.2,lateralOverlap:.2,color:'#80938c'},custom:{name:'Custom panel',length:3,width:2,overlap:0,lateralOverlap:0,color:'#848098'}};
const ASSETS={welfare:{name:'Welfare cabin',length:6,width:3},office:{name:'Site office',length:6,width:3},storage:{name:'Storage container',length:6.1,width:2.44},parking:{name:'Parking bay',length:5,width:2.5},generator:{name:'Generator',length:2.5,width:1.2},toilet:{name:'Toilet',length:1.2,width:1.2},skip:{name:'Skip',length:3.5,width:1.8},stage:{name:'Event stage',length:8,width:6},ramp:{name:'Ramp',length:.25,width:3},custom:{name:'Custom footprint',length:4,width:3}};
const TYPES={access:'Access route',egress:'Egress route',route:'Site route',area:'Site area',measure:'Measurement',service:'Services & constraints',hazard:'Concern area',note:'Site note',photo:'Site photo',panel:'Trakway panel',asset:'Site asset','hazard-marker':'Concern'};
const state={map:null,bases:{},base:'street',mode:'map',mapView:null,mapLocked:false,planLocked:true,group:null,draftGroup:null,editGroup:null,areaLayer:null,layers:new Map(),drawer:null,selected:null,tool:null,points:[],options:{},history:[],future:[],recognition:null,listening:false,voiceStarting:false,voices:[],voiceResultHandled:false,voiceError:false,request:null,areaGeneration:0,cache:new Map(),importKind:null,project:null};
function fresh(){return{format:'SAMI-PROJECT-2',name:'Untitled site',meta:{},area:null,features:[],base:'street',map:{center:{lat:52.5862,lng:-2.1288},zoom:16},hiddenTypes:[],serviceVisibility:Object.fromEntries(Object.keys(SERVICES).map(k=>[k,true])),route:{product:'lion',...PRODUCTS.lion,lanes:1},asset:{kind:'welfare',...ASSETS.welfare,angle:0},serviceType:'electric'};}
function feature(type,geometry,properties={}){return{type:'Feature',id:uid(),properties:{type,label:TYPES[type]||type,created:new Date().toISOString(),...properties},geometry};}
function cleanMeta(m){const o={};for(const [k,v]of Object.entries(m||{})){if(['__proto__','prototype','constructor'].includes(k))continue;if(['string','number','boolean'].includes(typeof v)||v===null)o[k]=v;}return o;}
function normaliseProject(p){const n=fresh();if(!p||!['SAMI-PROJECT-1','SAMI-PROJECT-2'].includes(p.format))throw Error('Choose a SAMI project backup.');n.name=String(p.name||n.name).slice(0,200);n.meta=cleanMeta(p.meta);n.area=G.validBounds(p.area)?p.area:null;const fs=p.features||p.geojson?.features||[];if(!Array.isArray(fs)||fs.length>12000)throw Error('The project has too many items.');n.features=fs.filter(G.validateFeature).map(f=>({...copy(f),id:typeof f.id==='string'?f.id:uid(),properties:cleanMeta(f.properties)}));if(['street','satellite','drawing'].includes(p.base))n.base=p.base;if(G.validCoord([p.map?.center?.lng,p.map?.center?.lat]))n.map={center:{lat:p.map.center.lat,lng:p.map.center.lng},zoom:Math.max(3,Math.min(23,Number(p.map.zoom)||16))};if(Array.isArray(p.hiddenTypes))n.hiddenTypes=p.hiddenTypes.filter(k=>TYPES[k]);if(p.serviceVisibility)for(const k of Object.keys(SERVICES))n.serviceVisibility[k]=p.serviceVisibility[k]!==false;if(p.route&&PRODUCTS[p.route.product])n.route={...n.route,...cleanMeta(p.route)};if(p.asset&&ASSETS[p.asset.kind])n.asset={...n.asset,...cleanMeta(p.asset)};if(SERVICES[p.serviceType])n.serviceType=p.serviceType;return n;}
function init(){
 if(!window.L||!G){$('#splashStatus').textContent='A required app file is missing. Re-upload the complete package.';return;}
 state.project=fresh();try{const raw=localStorage.getItem(LS_KEY);if(raw){state.project=normaliseProject(JSON.parse(raw));const legacy=JSON.parse(localStorage.getItem('sami.meta')||'{}');if(!Object.keys(state.project.meta).length)state.project.meta=cleanMeta(legacy);}}catch(e){toast('The saved project could not be read. Your stored copy has been kept.');}
 state.map=L.map('map',{zoomControl:false,preferCanvas:true,maxZoom:23,zoomSnap:.25,zoomDelta:1,doubleClickZoom:false,attributionControl:true}).setView(state.project.map.center,state.project.map.zoom);
 state.bases.street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxNativeZoom:19,maxZoom:23,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'});
 state.bases.satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:19,maxZoom:23,attribution:'Imagery © Esri'});
 state.group=L.featureGroup().addTo(state.map);state.draftGroup=L.featureGroup().addTo(state.map);state.editGroup=L.featureGroup().addTo(state.map);L.control.scale({position:'bottomright',imperial:false,maxWidth:100}).addTo(state.map);
 state.map.on('click',onMapClick);state.map.on('mousemove',e=>{$('#coordReadout').textContent=e.latlng.lat.toFixed(5)+', '+e.latlng.lng.toFixed(5);});
 state.map.on('moveend',()=>{if(state.mode!=='plan'){state.project.map={center:state.map.getCenter(),zoom:state.map.getZoom()};saveSoon();}});
 for(const b of Object.values(state.bases)){let warned=false;b.on('tileerror',()=>{if(!warned){warned=true;$('#sourceChip').textContent='Map imagery unavailable · drawing still works';}});}
 bindUI();switchBase(state.project.base,false);render();snapshot(true);initVoice();initToolRail();updateVoiceButton();$('#projectName').value=state.project.name;
 $('#welcomeCard').hidden=state.project.features.length>0||!!state.project.area||readPref('sami.welcome')==='seen';$('#splash').remove();
 new ResizeObserver(()=>{state.map.invalidateSize({pan:false});clampRail();if(state.mode==='plan'&&state.planLocked)fitArea();}).observe($('#workspace'));
 if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
 window.addEventListener('pagehide',()=>{saveNow();abortLayerRequest();});
}
function bindUI(){
 $('#homeBtn').onclick=()=>openDrawer('project');$('#projectBtn').onclick=()=>openDrawer('project');$('#searchBtn').onclick=()=>openDrawer('search');$('#exportBtn').onclick=openExport;
 $$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-base]').forEach(b=>b.onclick=()=>switchBase(b.dataset.base));$$('[data-drawer]').forEach(b=>b.onclick=()=>state.drawer===b.dataset.drawer?closeDrawer():openDrawer(b.dataset.drawer));
 $('#closeDrawer').onclick=closeDrawer;$('#areaChip').onclick=()=>openDrawer('area');$('#locateBtn').onclick=locate;$('#fitBtn').onclick=fitProject;$('#lockBtn').onclick=()=>setLock(!isLocked());$('#zoomInBtn').onclick=()=>state.map.zoomIn();$('#zoomOutBtn').onclick=()=>state.map.zoomOut();
 $('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#finishDrawBtn').onclick=finishDraw;$('#cancelDrawBtn').onclick=cancelDraw;$('#backPointBtn').onclick=backPoint;
 $('#projectName').onchange=()=>{state.project.name=$('#projectName').value.trim()||'Untitled site';commit();};
 $('#startFindBtn').onclick=()=>{dismissWelcome();openDrawer('search');};$('#dismissWelcome').onclick=dismissWelcome;
 $('#sendBtn').onclick=handleAskButton;$('#askInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendAsk();}};$('#askInput').oninput=updateAskLabel;
 $('#closeSami').onclick=()=>$('#samiPanel').classList.remove('open');$('#muteSami').onclick=()=>{setPref('sami.voice.output',readPref('sami.voice.output')==='off'?'on':'off');if(readPref('sami.voice.output')==='off')window.speechSynthesis?.cancel();updateVoiceButton();};
 $('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal();};$('#importInput').onchange=handleImport;$('#photoInput').onchange=handlePhoto;
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelDraw();closeModal();closeDrawer();return;}if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}else if(e.key==='Enter'&&state.tool){e.preventDefault();finishDraw();}else if((e.key==='Backspace'||e.key==='Delete')&&state.tool){e.preventDefault();backPoint();}});
}
function dismissWelcome(){$('#welcomeCard').hidden=true;setPref('sami.welcome','seen');}
function isLocked(){return state.mode==='plan'?state.planLocked:state.mapLocked;}
function setLock(value){if(state.mode==='plan')state.planLocked=value;else state.mapLocked=value;updateLock();toast(value?'View locked. Drawing tools still work.':'View unlocked. Drag or pinch to move.');}
function updateLock(){const locked=isLocked();['dragging','touchZoom','scrollWheelZoom','doubleClickZoom','boxZoom','keyboard'].forEach(k=>{if(state.map[k])state.map[k][locked?'disable':'enable']();});state.map.doubleClickZoom.disable();$('#lockBtn').classList.toggle('active',locked);$('#lockBtn').setAttribute('aria-pressed',String(locked));$('#lockBtn').innerHTML=(locked?'◆':'◇')+' <span>'+(locked?'Unlock':'Lock')+'</span>';$('#lockBtn').title=locked?'Unlock view':'Lock map';$('#zoomInBtn').disabled=locked;$('#zoomOutBtn').disabled=locked;}
function setMode(mode){
 if(mode==='plan'&&!state.project.area){openDrawer('area');toast('Define a plan area first, then open Plan drawing.');return false;}
 cancelDraw();closeDrawer();if(mode==='library'){state.modeBeforeLibrary=state.mode;setModeUI('library');openDrawer('library');return true;}
 if(state.mode!=='plan'&&mode==='plan'){state.mapView={center:state.map.getCenter(),zoom:state.map.getZoom(),base:state.base};state.planLocked=true;}
 const wasPlan=state.mode==='plan';state.mode=mode;setModeUI(mode);
 if(mode==='plan'){switchBase('drawing',false);fitArea();}else if(wasPlan){switchBase(state.mapView?.base||state.project.base||'street',false);if(state.mapView)state.map.setView(state.mapView.center,state.mapView.zoom);}
 updateLock();render();if(mode==='route')openDrawer('panels');else if(mode==='plan')openDrawer('draw');return true;
}
function setModeUI(mode){$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});$('#modeCaption').textContent={map:'Your site, in context',route:'Build access, panel by panel',plan:'One fixed area · shared with your map',library:'Panels, assets and your project items'}[mode];}
function switchBase(base,save=true){if(!['street','satellite','drawing'].includes(base))return;if(state.mode==='plan'&&base!=='drawing'){toast('Plan drawing stays fixed. Choose Map for live imagery.');return;}Object.values(state.bases).forEach(l=>{if(state.map.hasLayer(l))state.map.removeLayer(l);});if(state.bases[base])state.bases[base].addTo(state.map);state.base=base;$('#map').classList.toggle('drawing-base',base==='drawing');$$('[data-base]').forEach(b=>{const on=b.dataset.base===base;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.disabled=state.mode==='plan'&&b.dataset.base!=='drawing';});$('#sourceChip').textContent={street:'OpenStreetMap',satellite:'Esri imagery',drawing:'Scaled drawing · metres'}[base];if(save&&state.mode!=='plan'){state.project.base=base;saveSoon();}render();}
function fitArea(){if(!state.project.area)return;const b=state.project.area;state.map.fitBounds([[b[1],b[0]],[b[3],b[2]]],{paddingTopLeft:[window.innerWidth<760?82:98,112],paddingBottomRight:[window.innerWidth<760?65:83,105],maxZoom:23,animate:false});}
function fitProject(){if(state.project.area){fitArea();return;}if(state.group.getLayers().length)state.map.fitBounds(state.group.getBounds(),{padding:[100,120],maxZoom:22});else toast('Define a plan area or add an item first.');}
function latlng(c){return[c[1],c[0]];}function coord(ll){return[ll.lng,ll.lat];}
function areaText(){const b=state.project.area;if(!b)return'No plan area';const a=G.area(b);return a>=10000?(a/10000).toFixed(2)+' ha':Math.round(a).toLocaleString()+' m²';}
function visibleFeature(f){const m=f.properties;if(state.project.hiddenTypes.includes(m.type))return null;if(m.type==='service'&&state.project.serviceVisibility[m.serviceType]===false)return null;let geometry=f.geometry;if(state.project.area&&(m.type==='service'||state.mode==='plan'))geometry=G.clipGeometry(geometry,state.project.area);return geometry?{...f,geometry}:null;}
function featureStyle(f){const m=f.properties,t=m.type,c=SERVICES[m.serviceType]?.color;let style={color:'#174d43',weight:3,fillColor:'#72bc9c',fillOpacity:.12};if(t==='panel')style={color:'#476b58',weight:1,fillColor:PRODUCTS[m.product]?.color||'#9fbfa9',fillOpacity:.6};if(t==='asset')style={color:'#324c69',weight:2,fillColor:'#91b3c9',fillOpacity:.65};if(t==='service')style={color:c||'#9c6530',weight:3,dashArray:'8 5',fillColor:c,fillOpacity:.15};if(t==='access')style={color:'#008c77',weight:5};if(t==='egress')style={color:'#5b8625',weight:5,dashArray:'10 6'};if(t==='route')style={color:state.base==='drawing'?'#223934':'#365adb',weight:4};if(t==='measure')style={color:'#42444a',weight:2,dashArray:'5 5'};if(t==='hazard')style={color:'#c44545',weight:2,fillColor:'#e47166',fillOpacity:.2};if(f.id===state.selected)style={...style,color:'#00a885',weight:4};return style;}
function render(){if(!state.map)return;state.group.clearLayers();state.layers.clear();state.editGroup.clearLayers();
 for(const f of state.project.features){let shown;try{shown=visibleFeature(f);}catch{continue;}if(!shown)continue;const layer=L.geoJSON(shown,{style:()=>featureStyle(f),pointToLayer:(ff,ll)=>{const m=f.properties;if(m.type==='service')return L.circleMarker(ll,{...featureStyle(f),radius:6,fillOpacity:.8});const html=m.type==='photo'&&typeof m.data==='string'&&m.data.startsWith('data:image/')?'<img class="photo-marker" src="'+esc(m.data)+'" alt="Site photo">':'<div class="marker-note">'+(m.type==='hazard-marker'?'!':m.type==='photo'?'▣':'N')+'</div>';return L.marker(ll,{icon:L.divIcon({className:'',html,iconSize:[28,28],iconAnchor:[14,14]})});}});
 layer.on('click',e=>{if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);if(state.tool){onMapClick(e);return;}selectFeature(f.id);});
 if(f.properties.type==='measure')layer.bindTooltip(formatDistance(geometryLength(f.geometry)),{permanent:true,className:'map-label',direction:'center'});else if(['asset','note'].includes(f.properties.type))layer.bindTooltip(esc(f.properties.text||f.properties.label),{permanent:f.properties.type==='asset',className:'map-label',direction:'center'});
 layer.addTo(state.group);state.layers.set(f.id,layer);
 }
 if(state.areaLayer)state.map.removeLayer(state.areaLayer);if(state.project.area){const b=state.project.area;state.areaLayer=L.rectangle([[b[1],b[0]],[b[3],b[2]]],{color:'#098b69',weight:2,dashArray:'8 5',fillOpacity:0,interactive:false}).addTo(state.map);}
 $('#areaChip').textContent=state.project.area?'Plan area · '+areaText():'＋ Define plan area';updateLock();updateHistory();
}
function snapshot(initial=false){const s=JSON.stringify(state.project);if(initial){state.history=[s];state.future=[];}else if(s!==state.history.at(-1)){state.history.push(s);while(state.history.length>2&&(state.history.length>40||state.history.reduce((n,x)=>n+x.length,0)>20000000))state.history.shift();state.future=[];}updateHistory();}
function commit(){snapshot();render();saveSoon();}
function updateHistory(){if(!$('#undoBtn'))return;$('#undoBtn').disabled=state.tool?state.points.length===0:state.history.length<2;$('#redoBtn').disabled=!!state.tool||!state.future.length;}
function undo(){if(state.tool){backPoint();return;}if(state.history.length<2)return;abortLayerRequest();state.future.push(state.history.pop());restoreHistory(state.history.at(-1));toast('Undone.');}
function redo(){if(state.tool||!state.future.length)return;abortLayerRequest();const s=state.future.pop();state.history.push(s);restoreHistory(s);toast('Redone.');}
function restoreHistory(s){state.project=JSON.parse(s);state.areaGeneration++;state.cache.clear();state.selected=null;$('#projectName').value=state.project.name;if(state.mode==='plan'&&!state.project.area){state.mode='map';setModeUI('map');switchBase(state.project.base,false);}render();if(state.mode==='plan')fitArea();if(state.drawer)renderDrawer(state.drawer);saveSoon();}
let saveTimer;function saveSoon(){clearTimeout(saveTimer);$('#saveState').textContent='Saving…';saveTimer=setTimeout(saveNow,450);}
function saveNow(){clearTimeout(saveTimer);try{localStorage.setItem(LS_KEY,JSON.stringify(state.project));$('#saveState').textContent='Saved on this device';return true;}catch{$('#saveState').textContent='Export a backup';toast('Device storage is full. Export your project backup now.');return false;}}
function readPref(k){try{return localStorage.getItem(k);}catch{return null;}}function setPref(k,v){try{localStorage.setItem(k,v);}catch{}}
function startTool(tool,options={}){dismissWelcome();cancelDraw();closeDrawer();$('#samiPanel').classList.remove('open');state.selected=null;if((tool==='service')&&!state.project.area){openDrawer('area');toast('Define the area for service records first.');return;}state.tool=tool;state.options=copy(options);state.points=[];$('#drawStatus').hidden=false;$('#toolName').textContent=tool==='planArea'?'Define plan area':tool==='panelRoute'?'Build Trakway route':tool==='singlePanel'?'Place a panel':tool==='asset'?'Place '+options.label:TYPES[tool]||tool;renderDraft();}
function cancelDraw(){state.tool=null;state.points=[];state.options={};state.draftGroup?.clearLayers();state.editGroup?.clearLayers();if($('#drawStatus'))$('#drawStatus').hidden=true;updateHistory();}
function backPoint(){if(state.points.length){state.points.pop();renderDraft();}}
function snapped(c){if(!state.options.snap)return c;let best=c,score=13;const pt=state.map.latLngToContainerPoint(latlng(c));for(const f of state.project.features){if(!['panel','asset','area','route'].includes(f.properties.type))continue;const pts=f.geometry.type==='Polygon'?f.geometry.coordinates[0]:f.geometry.type==='LineString'?f.geometry.coordinates:[];for(const p of pts){const d=state.map.latLngToContainerPoint(latlng(p)).distanceTo(pt);if(d<score){score=d;best=p;}}}return best.slice();}
function onMapClick(e){if(!state.tool)return;const c=snapped(coord(e.latlng));if(state.mode==='plan'&&state.project.area&&!G.inside(c,state.project.area)){toast('Tap inside the defined plan area.');return;}if(state.tool==='service'&&!G.inside(c,state.project.area)){toast('Add service points inside the plan area.');return;}
 if(['asset','singlePanel','note','photo','hazard-marker'].includes(state.tool)){placeItem(c);return;}
 if(state.points.length&&G.distance(state.points.at(-1),c)<.02)return;state.points.push(c);renderDraft();if(['planArea','rectangle'].includes(state.tool)&&state.points.length===2)finishDraw();}
function renderDraft(){state.draftGroup.clearLayers();if(!state.tool)return;const ps=state.points,polygon=['area','hazard','planArea','rectangle'].includes(state.tool)||(state.tool==='service'&&state.options.area);let coords=ps;if(['planArea','rectangle'].includes(state.tool)&&ps.length===2){const b=boundsFromPoints(ps);coords=G.boundsGeometry(b).coordinates[0];}
 if(coords.length>1)(polygon&&coords.length>2?L.polygon(coords.map(latlng),{color:'#00a481',weight:3,fillOpacity:.14,interactive:false}):L.polyline(coords.map(latlng),{color:'#00a481',weight:3,dashArray:'6 5',interactive:false})).addTo(state.draftGroup);
 ps.forEach(p=>L.marker(latlng(p),{interactive:false,icon:L.divIcon({className:'',html:'<div class="draft-vertex"></div>',iconSize:[10,10],iconAnchor:[5,5]})}).addTo(state.draftGroup));
 const single=['asset','singlePanel','note','photo','hazard-marker'].includes(state.tool);$('#finishDrawBtn').hidden=single||state.tool==='planArea'||state.tool==='rectangle';$('#backPointBtn').hidden=single;$('#backPointBtn').disabled=!ps.length;$('#finishDrawBtn').disabled=ps.length<(polygon?3:2);$('#drawHint').textContent=single?'Tap the exact position on your map or plan.':state.tool==='planArea'||state.tool==='rectangle'?'Tap two opposite corners.':ps.length?`${ps.length} points · ${formatDistance(G.length(ps))} · Tap more, then Finish.`:'Tap points deliberately, then press Finish.';updateHistory();}
function boundsFromPoints(ps){return[Math.min(ps[0][0],ps[1][0]),Math.min(ps[0][1],ps[1][1]),Math.max(ps[0][0],ps[1][0]),Math.max(ps[0][1],ps[1][1])];}
function finishDraw(){const tool=state.tool,ps=copy(state.points),opt=copy(state.options);if(!tool)return;
 try{
 if(tool==='planArea'){if(ps.length<2)return;setArea(boundsFromPoints(ps));return;}
 if(tool==='panelRoute'){if(ps.length<2)return;const result=G.panels(ps,opt),id=uid();state.project.features.push(feature('route',{type:'LineString',coordinates:ps},{label:opt.name+' route',routeId:id,distance:result.distance,product:opt.product,generated:true}));for(const p of result.panels)state.project.features.push(feature('panel',p.geometry,{label:opt.name,product:opt.product,length:opt.length,width:opt.width,routeId:id,corner:p.corner,derived:true}));cancelDraw();commit();toast(`${result.panels.length} panels added · ${formatDistance(result.distance)}.`);openDrawer('panels');if(result.warnings.length)showModal('Review route corners','<p>'+result.warnings.map(esc).join('</p><p>')+'</p>');return;}
 const polygon=['area','hazard','rectangle'].includes(tool)||(tool==='service'&&opt.area);if(ps.length<(tool==='rectangle'?2:polygon?3:2))return;let geom=tool==='rectangle'?G.boundsGeometry(boundsFromPoints(ps)):polygon?{type:'Polygon',coordinates:[[...ps,ps[0].slice()]]}:{type:'LineString',coordinates:ps};
 if(polygon&&geom.type==='Polygon'&&Math.abs(signedArea(geom.coordinates[0]))<1e-16)throw Error('The area needs a non-zero width and height.');
 if(tool==='service'){geom=G.clipGeometry(geom,state.project.area);if(!geom)throw Error('No service geometry falls inside this plan area.');}
 const type=tool==='rectangle'?'area':tool,properties={...opt};if(tool==='measure')properties.distance=G.length(ps);state.project.features.push(feature(type,geom,properties));cancelDraw();commit();toast((TYPES[type]||'Item')+' added.');
 }catch(e){toast(e.message);}
}
function signedArea(r){let s=0;for(let i=1;i<r.length;i++)s+=r[i-1][0]*r[i][1]-r[i][0]*r[i-1][1];return s/2;}
function placeItem(c){const tool=state.tool,o=state.options;let f;if(tool==='asset'||tool==='singlePanel'){f=feature(tool==='asset'?'asset':'panel',G.rectangle(c,+o.length,+o.width,+o.angle||0),{...o,centerLng:c[0],centerLat:c[1]});}else f=feature(tool,{type:'Point',coordinates:c},{...o});state.project.features.push(f);cancelDraw();commit();toast('Item placed. Tap it to edit, move or rotate.');}
function setArea(b){if(!G.validBounds(b)||G.area(b)<1){toast('Choose a plan area larger than 1 m².');return;}if(G.area(b)>25000000){toast('Zoom in: keep each plan area below 25 km².');return;}abortLayerRequest();state.areaGeneration++;state.cache.clear();state.project.area=b;cancelDraw();commit();if(state.mode==='plan')fitArea();openDrawer('area');toast('Plan area saved. Map and Plan drawing share this area.');}
function useVisibleArea(){const sz=state.map.getSize(),x1=Math.min(100,sz.x*.2),y1=Math.min(125,sz.y*.25),x2=sz.x-Math.min(80,sz.x*.18),y2=sz.y-Math.min(115,sz.y*.25);setArea(boundsFromPoints([coord(state.map.containerPointToLatLng([x1,y1])),coord(state.map.containerPointToLatLng([x2,y2]))]));}
function geometryLength(g){return g.type==='LineString'?G.length(g.coordinates):g.type==='MultiLineString'?g.coordinates.reduce((s,l)=>s+G.length(l),0):0;}
function openDrawer(kind){dismissWelcome();if(state.tool)cancelDraw();$('#samiPanel').classList.remove('open');state.drawer=kind;const el=$('#drawer');el.classList.add('open');el.inert=false;el.setAttribute('aria-hidden','false');$$('[data-drawer]').forEach(b=>b.classList.toggle('active',b.dataset.drawer===kind));renderDrawer(kind);}
function closeDrawer(){state.drawer=null;$('#drawer').classList.remove('open');$('#drawer').inert=true;$('#drawer').setAttribute('aria-hidden','true');$$('[data-drawer]').forEach(b=>b.classList.remove('active'));if($('[data-mode="library"]').classList.contains('active'))setModeUI(state.mode);}
function section(s){return'<div class="section-title">'+s+'</div>';}function button(label,action,primary=false){return'<button class="wide-btn '+(primary?'primary':'')+'" data-action="'+action+'">'+label+'</button>';}
function field(id,label,value='',type='text',attrs=''){return'<label class="field-label" for="'+id+'">'+label+'</label><input class="field" id="'+id+'" type="'+type+'" value="'+esc(value)+'" '+attrs+'>';}
function choice(id,label,items,value){return'<label class="field-label" for="'+id+'">'+label+'</label><select class="field" id="'+id+'">'+Object.entries(items).map(([k,o])=>'<option value="'+k+'" '+(k===value?'selected':'')+'>'+esc(o.name||o)+'</option>').join('')+'</select>';}
function checkedRow(label,attrs,yes){return'<label class="switch-row"><span>'+label+'</span><input type="checkbox" '+attrs+' '+(yes?'checked':'')+'></label>';}
function renderDrawer(kind){const title={draw:'Draw on your site',panels:'Trakway panels',assets:'Place site assets',services:'Services & constraints',area:'Your plan area',layers:'Visible layers',library:'Your library',project:'Your project',search:'Find your site',help:'Find your tools',selection:'Edit item'};$('#drawerTitle').textContent=title[kind]||'SAMI';const box=$('#drawerContent');box.innerHTML=({draw:drawHTML,panels:panelsHTML,assets:assetsHTML,services:servicesHTML,area:areaHTML,layers:layersHTML,library:libraryHTML,project:projectHTML,search:searchHTML,help:helpHTML,selection:selectionHTML}[kind]||helpHTML)();box.onclick=e=>{const b=e.target.closest('[data-action]');if(b)runAction(b.dataset.action,b);};bindDrawer(kind);}
function drawHTML(){return'<p class="subtle">Choose a tool, then tap on the map. The same drawing appears in Plan drawing.</p><div class="tool-grid">'+[['route','Route line','Tap route points'],['access','Access route','Entry / approach'],['egress','Egress route','Exit / departure'],['area','Area boundary','Tap boundary points'],['rectangle','Rectangle','Two opposite corners'],['measure','Measure','Snaps to panel corners'],['note','Label / note','Place at a point'],['hazard','Concern area','Mark a restriction'],['photo','Site photo','Attach at a point']].map(([k,t,d])=>'<button data-action="draw:'+k+'">'+t+'<small>'+d+'</small></button>').join('')+'</div>'+section('More planning tools')+button('Build a panel route','open:panels')+button('Place a site asset','open:assets')+'<p class="subtle">Tap an existing item to edit, move, rotate or delete it. Undo remains available above the map.</p>';}
function panelsHTML(){const r=state.project.route,panels=state.project.features.filter(f=>f.properties.type==='panel');return'<p class="subtle">Choose a panel and run width. Tap a route, then Finish to generate full panels.</p>'+choice('panelProduct','Panel type',PRODUCTS,r.product)+'<div class="row equal"><div>'+field('panelLength','Along run (m)',r.length,'number','min="0.2" max="20" step="0.01"')+'</div><div>'+field('panelWidth','Across run (m)',r.width,'number','min="0.2" max="20" step="0.01"')+'</div></div>'+choice('panelLanes','Run width',{'1':{name:'1 panel wide'},'2':{name:'2 panels wide'},'3':{name:'3 panels wide'},'4':{name:'4 panels wide'}},String(r.lanes))+'<details><summary class="subtle" style="margin-top:13px;cursor:pointer">Joints & overlaps</summary><div class="row equal"><div>'+field('panelOverlap','Along run overlap (m)',r.overlap,'number','min="0" step="0.01"')+'</div><div>'+field('panelLateral','Side overlap (m)',r.lateralOverlap,'number','min="0" step="0.01"')+'</div></div><p class="subtle">Bend panels overlap at the join. Non-Sabre turns between 15° and 60° receive four extra inside panels on each meeting run. Sabre bends require joint and stagger review.</p></details>'+button('＋ Draw a Trakway route','panelRoute',true)+button('Place one panel','singlePanel')+'<div class="card row between"><span>Panels in this project</span><strong class="count">'+panels.length+'</strong></div>'+button('View materials schedule','open:library')+'<p class="subtle">Editable planning dimensions carried forward from your earlier app; Sabre-X uses a 4 × 2 m footprint. Confirm dimensions and joint arrangement for the product used.</p>';}
function assetsHTML(){const a=state.project.asset;return'<p class="subtle">Select a footprint, set its size and tap its position. Sizes are editable planning defaults.</p><div class="asset-list">'+Object.entries(ASSETS).map(([k,v])=>'<button class="'+(a.kind===k?'active':'')+'" data-action="assetChoice:'+k+'">'+v.name+'<small>'+v.length+' × '+v.width+' m</small></button>').join('')+'</div>'+field('assetLabel','Label',a.name)+'<div class="row equal"><div>'+field('assetLength','Length (m)',a.length,'number','min="0.1" max="500" step="0.1"')+'</div><div>'+field('assetWidth','Width (m)',a.width,'number','min="0.1" max="500" step="0.1"')+'</div></div>'+field('assetAngle','Rotation clockwise from north (°)',a.angle,'number','step="5"')+button('＋ Place on map / plan','placeAsset',true);}
function areaHTML(){const b=state.project.area;return'<p class="subtle">This is the shared area for your site plan. Service records are clipped to it. Panning the wider map does not load more records.</p>'+(b?'<div class="card"><span class="tag">PLAN AREA DEFINED</span><h3 style="margin:12px 0 4px">'+areaText()+'</h3><div class="subtle">'+formatDistance(G.distance([b[0],b[1]],[b[2],b[1]]))+' east–west × '+formatDistance(G.distance([b[0],b[1]],[b[0],b[3]]))+' north–south</div></div>':'<div class="card subtle">Find your site and zoom in before setting the area.</div>')+button(b?'Redefine with two corners':'Define with two corners','defineArea',true)+button('Use visible map area','visibleArea')+(b?button('Open fixed plan drawing','planMode')+button('Fit plan area to screen','fitArea')+button('Add services to this area','open:services'):'')+'<p class="subtle">Plan drawing fits this area into the window and starts locked. Unlock temporarily to zoom into a detail. Edits stay in the same geographic positions in Map view.</p>';}
function servicesHTML(){const s=state.project,has=!!s.area,counts={};s.features.filter(f=>f.properties.type==='service').forEach(f=>{if(visibleFeature({...f,properties:{...f.properties,serviceType:'__count__'}}))counts[f.properties.serviceType]=(counts[f.properties.serviceType]||0)+1;});return'<div class="card"><span class="tag">'+(has?'PLAN AREA ONLY · '+areaText():'DEFINE A PLAN AREA FIRST')+'</span><p class="subtle">Tick the types to display. Add a record below or import project data; a tick cannot create missing service records.</p></div>'+(!has?button('Define the service search area','open:area',true):'')+section('Show these types')+Object.entries(SERVICES).map(([k,v])=>checkedRow('<i class="swatch" style="background:'+v.color+'"></i>'+v.name+' <span class="tag muted">'+(counts[k]||0)+'</span>','data-service-toggle="'+k+'"',s.serviceVisibility[k])).join('')+section('Add a record')+choice('serviceType','Record type',SERVICES,s.serviceType)+field('serviceLabel','Record label','')+field('serviceSource','Source / drawing reference','', 'text','placeholder="e.g. survey drawing U-04, Rev C"')+button('＋ Draw selected service / area','drawService',true)+button('Import records · GeoJSON','importServices')+'<p class="subtle">Water, gas and electricity draw as lines. Ecology, SSSI, tree protection and heritage draw as areas. Imported WGS84 GeoJSON may contain points, lines or areas.</p>'+section('Connected records')+'<div class="card"><div class="subtle">'+((window.SAMI_CONFIG?.serviceSources||[]).length?'An area-query source is configured. Load explicitly when you need an update.':'No live utility or constraint source is configured. Use your survey / project records above.')+'</div>'+button('Load selected layers in plan area','loadServices')+'<div id="layerLoadStatus" class="subtle">'+esc(state.lastLoad||'No background loading while the map moves.')+'</div></div>';}
function layersHTML(){return'<p class="subtle">Choose which project items are visible. Hidden items remain saved.</p>'+Object.entries(TYPES).map(([k,v])=>checkedRow(v,'data-type-toggle="'+k+'"',!state.project.hiddenTypes.includes(k))).join('')+button('Choose service types','open:services')+button('Open materials library','open:library');}
function libraryHTML(){const fs=state.project.features,p=fs.filter(f=>f.properties.type==='panel'),assets=fs.filter(f=>f.properties.type==='asset'),counts={};p.forEach(f=>{const key=f.properties.label+'|'+f.properties.length+'|'+f.properties.width;counts[key]=(counts[key]||0)+1;});return'<div class="row equal">'+button('Add panels','open:panels',true)+button('Add assets','open:assets')+'</div>'+section('Materials schedule')+'<div class="card row between"><div><strong class="count">'+p.length+'</strong> panels</div><div><strong class="count">'+assets.length+'</strong> assets</div></div>'+Object.entries(counts).map(([k,n])=>{const [label,l,w]=k.split('|');return'<div class="item-row"><div><strong>'+esc(label)+'</strong><small>'+esc(l)+' × '+esc(w)+' m</small></div><b>'+n+'</b></div>';}).join('')+button('Download materials CSV','csv')+section('Routes, areas and assets')+(fs.filter(f=>f.properties.type!=='panel').slice(0,200).map(f=>'<div class="item-row"><div><strong>'+esc(f.properties.label)+'</strong><small>'+esc(TYPES[f.properties.type]||f.properties.type)+'</small></div><button class="mini-btn" data-action="select:'+esc(f.id)+'">Edit</button></div>').join('')||'<p class="subtle">Items appear here as you build your plan.</p>')+(fs.filter(f=>f.properties.type!=='panel').length>200?'<p class="subtle">Showing the first 200 items. All items are included in exports.</p>':'');}
function projectHTML(){const m=state.project.meta;return field('projectNameEdit','Project name',state.project.name)+field('siteRef','Site reference',m.siteRef||'')+field('clientName','Client / contractor',m.clientName||'')+'<label class="field-label" for="siteNotes">Site notes</label><textarea class="field" id="siteNotes" rows="3">'+esc(m.siteNotes||'')+'</textarea>'+section('Project files')+button('Save on this device','save')+button('Export editable backup','backup')+button('Restore a SAMI backup','restore')+button('New project','new')+section('Ask SAMI voice')+checkedRow('Talk-back using an available device voice','id="voiceOutput"',readPref('sami.voice.output')!=='off')+'<label class="field-label" for="samiVoiceSelect">Spoken voice</label><select class="field" id="samiVoiceSelect"></select>'+button('Test SAMI voice','testVoice')+'<p class="subtle">Voice capture depends on microphone permission and browser support. There is one Ask SAMI button: tap to speak, or submit text if the field is filled.</p>'+button('Reset toolbar position','resetRail');}
function searchHTML(){return'<p class="subtle">Search a postcode or place, or enter coordinates. Map scale is calculated automatically.</p><label class="field-label" for="placeQuery">Postcode, address or place</label><div class="row"><input class="field" id="placeQuery" placeholder="e.g. Wolverhampton"><button class="mini-btn" data-action="search">Find</button></div><div id="placeResults"></div>'+button('Use my current location','locate')+section('Coordinates')+field('latInput','Latitude','', 'number','step="any"')+field('lngInput','Longitude','', 'number','step="any"')+button('Go to coordinates','coords');}
function helpHTML(){return[['1 · Find the site','Use Find site or the location button on the right. Map / Satellite / Drawing changes the background.'],['2 · Define the plan area','Open Plan area on the side. Tap two corners or use the visible area.'],['3 · Build your plan','Route plan opens Trakway panels. Draw and Assets on the side expose the other site tools. Tap points, then Finish.'],['4 · Work in either view','Plan drawing fits the defined area to the window. It uses exactly the same items as Map. Lock prevents map movement while you draw.'],['5 · Add service records','Services → choose type → draw a record or import GeoJSON. Tick types to show them. External layers load only when requested, within your area.'],['6 · Edit and recover','Tap an item to rename, move, rotate or edit its points. Undo / Redo stay above the map. Export a SAMI backup to transfer your editable project.'],['Keep the view clear','Use the dotted handle to move the side toolbar. Collapse it with the chevron. Tap a side label to open or close its drawer.']].map(([t,d])=>'<div class="help-step"><strong>'+t+'</strong><p>'+d+'</p></div>').join('');}
function bindDrawer(kind){
 if(kind==='panels')$('#panelProduct').onchange=()=>{const product=$('#panelProduct').value;state.project.route={product,...PRODUCTS[product],lanes:state.project.route.lanes};renderDrawer('panels');saveSoon();};
 if(kind==='services'){ $$('[data-service-toggle]').forEach(el=>el.onchange=()=>{abortLayerRequest();state.project.serviceVisibility[el.dataset.serviceToggle]=el.checked;commit();});$('#serviceType').onchange=()=>{state.project.serviceType=$('#serviceType').value;saveSoon();};}
 if(kind==='layers')$$('[data-type-toggle]').forEach(el=>el.onchange=()=>{state.project.hiddenTypes=state.project.hiddenTypes.filter(x=>x!==el.dataset.typeToggle);if(!el.checked)state.project.hiddenTypes.push(el.dataset.typeToggle);commit();});
 if(kind==='project'){['siteRef','clientName','siteNotes'].forEach(id=>$('#'+id).onchange=()=>{state.project.meta[id]=$('#'+id).value;commit();});$('#projectNameEdit').onchange=()=>{state.project.name=$('#projectNameEdit').value.trim()||'Untitled site';$('#projectName').value=state.project.name;commit();};$('#voiceOutput').onchange=()=>{setPref('sami.voice.output',$('#voiceOutput').checked?'on':'off');updateVoiceButton();if(!$('#voiceOutput').checked)window.speechSynthesis?.cancel();};populateVoiceSelect();$('#samiVoiceSelect').onchange=()=>setPref('sami.voice.name',$('#samiVoiceSelect').value);}
 if(kind==='search')$('#placeQuery').onkeydown=e=>{if(e.key==='Enter')findPlace();};
}
function readPanelOptions(){const o={product:$('#panelProduct').value,name:PRODUCTS[$('#panelProduct').value].name,length:Number($('#panelLength').value),width:Number($('#panelWidth').value),overlap:Number($('#panelOverlap').value),lateralOverlap:Number($('#panelLateral').value),lanes:Number($('#panelLanes').value)};G.panels([[0,52],[.00001,52]],o);state.project.route=copy(o);return o;}
function startNote(){showModal('Add a site note',field('newNote','Text','')+button('Choose its position','placeNote',true));$('#modalBody').onclick=e=>{if(e.target.closest('[data-action="placeNote"]')){const text=$('#newNote').value.trim();if(!text)return;closeModal();startTool('note',{text,label:text});}};$('#newNote').focus();}
function runAction(action,b){try{
 const [cmd,...parts]=action.split(':');const arg=parts.join(':');if(cmd==='open'){openDrawer(arg);return;}if(cmd==='draw'){if(arg==='note')startNote();else if(arg==='photo')$('#photoInput').click();else startTool(arg,{snap:arg==='measure'});return;}if(cmd==='assetChoice'){state.project.asset={kind:arg,...ASSETS[arg],angle:0};renderDrawer('assets');return;}if(cmd==='select'){selectFeature(arg,true);return;}
 if(action==='panelRoute'){startTool('panelRoute',readPanelOptions());return;}if(action==='singlePanel'){const o=readPanelOptions();startTool('singlePanel',{...o,label:o.name,angle:0});return;}if(action==='placeAsset'){const a={kind:state.project.asset.kind,name:$('#assetLabel').value.trim()||'Site asset',length:+$('#assetLength').value,width:+$('#assetWidth').value,angle:+$('#assetAngle').value||0};if(!(a.length>.1&&a.length<=500&&a.width>.1&&a.width<=500))throw Error('Enter footprint dimensions between 0.1 and 500 metres.');state.project.asset=copy(a);startTool('asset',{...a,label:a.name});return;}
 if(action==='drawService'){if(!state.project.area){openDrawer('area');return;}const k=$('#serviceType').value,v=SERVICES[k];state.project.serviceVisibility[k]=true;state.project.hiddenTypes=state.project.hiddenTypes.filter(t=>t!=='service');startTool('service',{serviceType:k,area:!!v.area,label:$('#serviceLabel').value.trim()||v.name,source:$('#serviceSource').value.trim()||'Manual field record',verification:'Unverified',provenance:'Field observation'});return;}
 if(action==='defineArea'){if(state.mode==='plan')setMode('map');startTool('planArea');return;}if(action==='visibleArea'){useVisibleArea();return;}if(action==='planMode'){setMode('plan');return;}if(action==='fitArea'){closeDrawer();fitArea();return;}
 if(action==='importServices'){if(!state.project.area){openDrawer('area');return;}state.importKind='services';state.importServiceType=$('#serviceType').value;$('#importInput').click();return;}if(action==='loadServices'){loadServices();return;}if(action==='restore'){state.importKind='project';$('#importInput').click();return;}
 if(action==='search'){findPlace();return;}if(action==='coords'){goCoords();return;}if(action==='locate'){locate();return;}if(action==='save'){if(saveNow())toast('Project saved on this device.');return;}if(action==='backup'){exportProjectJSON();return;}if(action==='csv'){exportCSV();return;}if(action==='testVoice'){primeSpeech();speakOptional('SAMI is ready. You can ask me to open panels, lock the map, or switch to your site plan.',true);return;}
 if(action==='resetRail'){setPref('sami.toolrail','{}');$('#toolRail').style.left='';$('#toolRail').style.top='';$('#toolRail').classList.remove('collapsed');updateRailButton();toast('Toolbar position reset.');return;}
 if(action==='new'){showModal('Start a new project?','<p>Your current project will be cleared from the workspace. Export a backup to keep a separate copy.</p>'+button('Export current backup','backup')+button('Start new project','confirmNew',true));$('#modalBody').onclick=e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='backup')exportProjectJSON();if(a==='confirmNew'){state.project=fresh();abortLayerRequest();state.cache.clear();state.areaGeneration++;state.selected=null;state.mode='map';setModeUI('map');cancelDraw();closeModal();closeDrawer();$('#projectName').value=state.project.name;switchBase('street',false);commit();toast('New project. Undo restores the previous workspace.');}};return;}
 if(action.startsWith('edit'))editAction(action);
 }catch(e){toast(e.message);}}
function selectFeature(id,fit=false){const f=state.project.features.find(f=>f.id===id);if(!f)return;cancelDraw();state.selected=id;render();openDrawer('selection');if(fit){const g=state.layers.get(id);if(g?.getBounds().isValid())state.map.fitBounds(g.getBounds().pad(.35),{maxZoom:21,padding:[120,130]});}}
function selectionHTML(){const f=state.project.features.find(f=>f.id===state.selected);if(!f)return'<p class="subtle">Tap an item to edit it.</p>';const m=f.properties;return'<span class="tag">'+esc(TYPES[m.type]||m.type)+'</span>'+field('editLabel','Label',m.text||m.label)+(m.source?'<div class="card subtle">Source: '+esc(m.source)+'<br>Status: '+esc(m.verification||'Unverified')+'</div>':'')+button('Save label','editLabel',true)+(['asset','panel'].includes(m.type)?field('editAngle','Rotate clockwise (°)',0,'number','step="5"')+button('Apply rotation','editRotate'):'')+button('Move whole item','editMove')+(!m.derived&&!m.sourceId&&!['asset','panel'].includes(m.type)?button('Edit drawing points','editVertices'):'')+(m.routeId?button('Delete this complete panel run','editDeleteRun'):'')+button('Delete item','editDelete');}
function editAction(action){const f=state.project.features.find(f=>f.id===state.selected);if(!f)return;
 if(action==='editLabel'){f.properties.label=$('#editLabel').value.trim()||TYPES[f.properties.type];if(f.properties.type==='note')f.properties.text=f.properties.label;commit();toast('Label updated.');}
 if(action==='editDelete'||action==='editDeleteRun'){const id=f.id,r=f.properties.routeId;state.project.features=state.project.features.filter(x=>action==='editDeleteRun'?x.properties.routeId!==r:x.id!==id);state.selected=null;commit();closeDrawer();toast('Deleted. Undo is available.');}
 if(action==='editRotate'){const a=(+$('#editAngle').value||0)*Math.PI/180,b=G.boundsOf(f.geometry),center=[(b[0]+b[2])/2,(b[1]+b[3])/2],p=G.projection(center);transformGeometry(f.geometry,c=>{const[x,y]=p.xy(c);return p.ll([x*Math.cos(a)+y*Math.sin(a),-x*Math.sin(a)+y*Math.cos(a)]);});commit();toast('Rotation applied.');}
 if(action==='editMove'){closeDrawer();const b=G.boundsOf(f.geometry),p=[(b[0]+b[2])/2,(b[1]+b[3])/2],marker=editMarker(p);marker.bindTooltip('Drag to move',{permanent:true,className:'map-label'});marker.on('dragend',()=>{const next=coord(marker.getLatLng()),delta=[next[0]-p[0],next[1]-p[1]],old=copy(f.geometry);transformGeometry(f.geometry,c=>[c[0]+delta[0],c[1]+delta[1]]);if(f.properties.type==='service'&&state.project.area){const clipped=G.clipGeometry(f.geometry,state.project.area);if(!clipped){f.geometry=old;toast('Keep service records inside the plan area.');render();return;}f.geometry=clipped;}commit();toast('Item moved.');});toast('Drag the white handle to move the item.');}
 if(action==='editVertices'){closeDrawer();const g=f.geometry;let pts=g.type==='Point'?[g.coordinates]:g.type==='LineString'?g.coordinates:g.type==='Polygon'&&g.coordinates.length===1?g.coordinates[0].slice(0,-1):null;if(!pts||pts.length>150){toast('This imported geometry has too many parts to edit here.');return;}pts.forEach((p,i)=>{const marker=editMarker(p);marker.on('dragend',()=>{let next=coord(marker.getLatLng());if(f.properties.type==='service'&&state.project.area&&!G.inside(next,state.project.area)){marker.setLatLng(latlng(p));toast('Keep points inside the plan area.');return;}if(g.type==='Point')g.coordinates=next;else if(g.type==='LineString')g.coordinates[i]=next;else{g.coordinates[0][i]=next;if(i===0)g.coordinates[0][g.coordinates[0].length-1]=next.slice();}if(f.properties.type==='measure')f.properties.distance=geometryLength(g);commit();toast('Point moved. Tap Edit drawing points to continue.');});});toast('Drag a white point. Each move can be undone.');}
}
function editMarker(p){return L.marker(latlng(p),{draggable:true,icon:L.divIcon({className:'',html:'<div class="vertex-handle"></div>',iconSize:[17,17],iconAnchor:[8,8]})}).addTo(state.editGroup);}
function transformGeometry(g,fn){function walk(a){if(typeof a[0]==='number')return fn(a);return a.map(walk);}g.coordinates=walk(g.coordinates);}
async function findPlace(){const q=$('#placeQuery')?.value.trim(),out=$('#placeResults');if(!q||!out)return;out.innerHTML='<p class="subtle">Searching…</p>';try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=6&q='+encodeURIComponent(q),{signal:AbortSignal.timeout(10000),headers:{Accept:'application/json'}});if(!r.ok)throw Error();const data=await r.json();if(!out.isConnected)return;out.innerHTML=data.length?data.map((x,i)=>'<button class="wide-btn" data-place="'+i+'">'+esc(x.display_name)+'</button>').join(''):'<p class="subtle">No matches found. Try a postcode or coordinates.</p>';out.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{const x=data[+b.dataset.place];goTo([+x.lon,+x.lat]);});}catch{if(out.isConnected)out.innerHTML='<p class="subtle">Search is unavailable. Use coordinates or current location.</p>';}}
function goCoords(){const p=[Number($('#lngInput').value),Number($('#latInput').value)];if(!$('#latInput').value||!$('#lngInput').value||!G.validCoord(p)){toast('Enter valid latitude and longitude.');return;}goTo(p);}
function goTo(c){if(state.mode==='plan')setMode('map');closeDrawer();dismissWelcome();state.map.setView(latlng(c),18);}
function locate(){if(!navigator.geolocation){toast('Location is unavailable.');return;}toast('Finding your location…');navigator.geolocation.getCurrentPosition(p=>{const c=[p.coords.longitude,p.coords.latitude];goTo(c);const m=L.circleMarker(latlng(c),{color:'#fff',weight:3,radius:7,fillColor:'#0875f5',fillOpacity:1}).addTo(state.map);setTimeout(()=>state.map.removeLayer(m),12000);},()=>toast('Location could not be read. Allow permission or enter coordinates.'),{enableHighAccuracy:true,timeout:10000});}
async function handlePhoto(ev){const f=ev.target.files?.[0];ev.target.value='';if(!f)return;if(!f.type.startsWith('image/')){toast('Choose an image file.');return;}try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});const im=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=data;});const scale=Math.min(1,1200/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*scale;c.height=im.height*scale;c.getContext('2d').drawImage(im,0,0,c.width,c.height);startTool('photo',{label:f.name,name:f.name,data:c.toDataURL('image/jpeg',.76)});}catch{toast('This image could not be opened. Try a JPEG or PNG.');}}
function sourceFeatures(data){if(data?.crs&&!/4326|CRS84/i.test(JSON.stringify(data.crs)))throw Error('Export the source as WGS84 GeoJSON (EPSG:4326 / CRS84).');const fs=data?.type==='FeatureCollection'?data.features:data?.type==='Feature'?[data]:null;if(!Array.isArray(fs))throw Error('Choose a GeoJSON FeatureCollection or Feature.');if(fs.length>10000)throw Error('The file exceeds 10,000 records. Export a smaller site area.');return fs;}
function prepareServices(data,source,fallback,selectedOnly=true){const results=[],skipped={outside:0,invalid:0,hidden:0};for(const f of sourceFeatures(data)){if(!G.validateFeature(f)){skipped.invalid++;continue;}const m=cleanMeta(f.properties),type=SERVICES[m.serviceType]?m.serviceType:SERVICES[m.service_type]?m.service_type:fallback;if(selectedOnly&&state.project.serviceVisibility[type]===false){skipped.hidden++;continue;}let geometry;try{geometry=G.clipGeometry(f.geometry,state.project.area);}catch{skipped.invalid++;continue;}if(!geometry){skipped.outside++;continue;}results.push(feature('service',geometry,{...m,type:'service',serviceType:type,label:m.label||m.name||SERVICES[type].name,source:m.source||source,sourceId:source,verification:m.verification||'Unverified',provenance:m.provenance||'Imported project record',imported:new Date().toISOString()}));}return{results,skipped};}
async function handleImport(ev){const file=ev.target.files?.[0];ev.target.value='';if(!file)return;try{if(file.size>12*1024*1024)throw Error('Choose a file smaller than 12 MB.');const data=JSON.parse(await file.text());if(state.importKind==='project'){const p=normaliseProject(data);showModal('Restore this project?','<p>Restore <strong>'+esc(p.name)+'</strong> with '+p.features.length+' items. This replaces the workspace; Undo can restore the current one.</p>'+button('Restore project','confirmRestore',true));$('#modalBody').onclick=e=>{if(e.target.closest('[data-action="confirmRestore"]')){cancelDraw();abortLayerRequest();state.project=p;state.areaGeneration++;state.cache.clear();state.selected=null;state.mode='map';setModeUI('map');$('#projectName').value=p.name;closeModal();closeDrawer();switchBase(p.base,false);state.map.setView(p.map.center,p.map.zoom);commit();if(p.area)fitArea();toast('Project restored.');}};return;}
 if(!state.project.area)throw Error('Define a plan area before importing services.');const k=state.importServiceType||state.project.serviceType;state.project.serviceVisibility[k]=true;state.project.hiddenTypes=state.project.hiddenTypes.filter(t=>t!=='service');const {results,skipped}=prepareServices(data,file.name,k,false);if(state.project.features.length+results.length>12000)throw Error('This project exceeds 12,000 items. Split the project.');const sourceId='file:'+file.name;results.forEach(f=>{f.properties.sourceId=sourceId;});state.project.features=state.project.features.filter(f=>f.properties.sourceId!==sourceId);state.project.features.push(...results);commit();state.lastLoad=results.length+' records imported into plan area. '+skipped.outside+' outside, '+skipped.hidden+' hidden types, '+skipped.invalid+' unsupported / invalid.';openDrawer('services');toast(state.lastLoad);
 }catch(e){toast('Import: '+e.message);}}
function abortLayerRequest(){state.request?.abort();state.request=null;}
async function boundedJSON(response,max=4*1024*1024){if(!response.ok)throw Error('Source returned HTTP '+response.status);if(+response.headers.get('content-length')>max)throw Error('Source response is too large. Query a smaller plan area.');if(!response.body){const t=await response.text();if(t.length>max)throw Error('Source response is too large.');return JSON.parse(t);}const reader=response.body.getReader(),parts=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw Error('Source response is too large.');}parts.push(value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;parts.forEach(p=>{bytes.set(p,offset);offset+=p.length;});return JSON.parse(new TextDecoder().decode(bytes));}
async function loadServices(){
 const area=state.project.area,selected=Object.keys(SERVICES).filter(k=>state.project.serviceVisibility[k]);if(!area){openDrawer('area');return;}if(!selected.length){toast('Select at least one service or constraint type.');return;}
 const sources=(window.SAMI_CONFIG?.serviceSources||[]).filter(s=>s.enabled!==false&&s.url&&selected.includes(s.type));if(!sources.length){state.lastLoad='No source connected for the selected types. Draw or import your project records.';renderDrawer('services');toast(state.lastLoad);return;}
 abortLayerRequest();const controller=new AbortController();state.request=controller;const generation=state.areaGeneration,bbox=area.join(','),captured=JSON.stringify(selected);state.lastLoad='Loading records for this plan area…';renderDrawer('services');const pending=[],errors=[];const timer=setTimeout(()=>controller.abort(),20000);
 try{for(const s of sources){if(controller.signal.aborted)break;try{const sourceId='source:'+s.url+':'+s.type,key=sourceId+'|'+bbox,hit=state.cache.get(key);let data;if(hit&&Date.now()-hit.time<300000)data=hit.data;else{const url=new URL(s.url,location.href);if(url.protocol!=='https:'&&url.origin!==location.origin)throw Error('Use an HTTPS data source.');url.searchParams.set('bbox',bbox);url.searchParams.set('crs','EPSG:4326');url.searchParams.set('limit','10000');data=await boundedJSON(await fetch(url.href,{signal:controller.signal,headers:{Accept:'application/geo+json,application/json'}}));state.cache.set(key,{data,time:Date.now()});if(state.cache.size>10)state.cache.delete(state.cache.keys().next().value);}if(controller.signal.aborted)break;const res=prepareServices(data,s.name||s.url,s.type);res.results.forEach(f=>{f.properties.sourceId=sourceId;f.properties.source=s.name||s.url;});pending.push({sourceId,features:res.results});}catch(e){if(e.name!=='AbortError')errors.push((s.name||s.type)+': '+e.message);}}
 if(controller.signal.aborted||generation!==state.areaGeneration||bbox!==state.project.area?.join(',')||captured!==JSON.stringify(Object.keys(SERVICES).filter(k=>state.project.serviceVisibility[k]))){state.lastLoad='Load stopped. Run Load selected layers for the current area.';return;}
 let next=state.project.features;pending.forEach(batch=>{next=next.filter(f=>f.properties.sourceId!==batch.sourceId).concat(batch.features);});if(next.length>12000)throw Error('Too many records for this project. Use a smaller area.');state.project.features=next;state.project.hiddenTypes=state.project.hiddenTypes.filter(t=>t!=='service');commit();state.lastLoad=pending.reduce((n,b)=>n+b.features.length,0)+' records loaded inside this plan area.'+(errors.length?' '+errors.join(' '):'');
 }catch(e){state.lastLoad=e.message;}finally{clearTimeout(timer);if(state.request===controller)state.request=null;if(state.drawer==='services')renderDrawer('services');toast(state.lastLoad);}
}
function formatDistance(n){return n>=1000?(n/1000).toFixed(2)+' km':n.toFixed(n<100?1:0)+' m';}
function safeName(){return state.project.name.replace(/[^a-z0-9_-]+/gi,'_')||'SAMI_Project';}
function download(name,text,type){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function projectGeoJSON(){const features=copy(state.project.features);if(state.project.area)features.unshift(feature('plan-area',G.boundsGeometry(state.project.area),{label:'Defined plan area'}));features.forEach(f=>{delete f.properties.data;});return{type:'FeatureCollection',name:state.project.name,features};}
function exportProjectJSON(){saveNow();download(safeName()+'_SAMI_project.json',JSON.stringify(state.project,null,2),'application/json');}
function exportGeoJSON(){download(safeName()+'_SAMI.geojson',JSON.stringify(projectGeoJSON(),null,2),'application/geo+json');}
function exportCSV(){const rows=[['Item','Type','Length (m)','Width (m)','Quantity','Source / reference']],groups=new Map();for(const f of state.project.features){const m=f.properties;if(['panel','asset'].includes(m.type)){const k=[m.label,m.type,m.length,m.width].join('|');if(!groups.has(k))groups.set(k,[m.label,m.type,m.length||'',m.width||'',0,'']);groups.get(k)[4]++;}else rows.push([m.label,TYPES[m.type]||m.type,m.type==='measure'?geometryLength(f.geometry).toFixed(2):'','',1,m.source||'']);}rows.push(...groups.values());const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';download(safeName()+'_materials.csv','\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
function exportKML(){function geom(g){const coords=ps=>ps.map(c=>c[0]+','+c[1]+',0').join(' ');if(g.type==='Point')return'<Point><coordinates>'+coords([g.coordinates])+'</coordinates></Point>';if(g.type==='LineString')return'<LineString><coordinates>'+coords(g.coordinates)+'</coordinates></LineString>';if(g.type==='Polygon')return'<Polygon>'+g.coordinates.map((r,i)=>'<'+(i?'inner':'outer')+'BoundaryIs><LinearRing><coordinates>'+coords(r)+'</coordinates></LinearRing></'+(i?'inner':'outer')+'BoundaryIs>').join('')+'</Polygon>';const map={MultiPoint:'Point',MultiLineString:'LineString',MultiPolygon:'Polygon'};return'<MultiGeometry>'+g.coordinates.map(c=>geom({type:map[g.type],coordinates:c})).join('')+'</MultiGeometry>';}
 const out='<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>'+esc(state.project.name)+'</name>'+projectGeoJSON().features.map(f=>'<Placemark><name>'+esc(f.properties.label)+'</name>'+geom(f.geometry)+'</Placemark>').join('')+'</Document></kml>';download(safeName()+'_SAMI.kml',out,'application/vnd.google-earth.kml+xml');}
function exportDXF(){const gj=projectGeoJSON(),origin=state.project.area?state.project.area.slice(0,2):coord(state.map.getCenter()),pr=G.projection(origin);let out='999\nSAMI local metres; origin longitude '+origin[0]+' latitude '+origin[1]+'\n0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n6\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n';function geom(g,layer){if(g.type==='Point'){const[x,y]=pr.xy(g.coordinates);out+='0\nPOINT\n8\n'+layer+'\n10\n'+x+'\n20\n'+y+'\n30\n0\n';}else if(g.type==='LineString'){out+='0\nLWPOLYLINE\n8\n'+layer+'\n90\n'+g.coordinates.length+'\n70\n0\n';g.coordinates.forEach(c=>{const[x,y]=pr.xy(c);out+='10\n'+x.toFixed(3)+'\n20\n'+y.toFixed(3)+'\n';});}else if(g.type==='Polygon')g.coordinates.forEach(r=>geom({type:'LineString',coordinates:r},layer));else{const map={MultiPoint:'Point',MultiLineString:'LineString',MultiPolygon:'Polygon'};g.coordinates.forEach(c=>geom({type:map[g.type],coordinates:c},layer));}}
 gj.features.forEach(f=>geom(f.geometry,(f.properties.serviceType||f.properties.type||'SAMI').replace(/[^a-z0-9_-]/gi,'_').toUpperCase()));out+='0\nENDSEC\n0\nEOF\n';download(safeName()+'_SAMI.dxf',out,'application/dxf');}
function openExport(){cancelDraw();showModal('Export your site plan','<p class="subtle">The editable backup preserves the whole project. GeoJSON and KML retain geographic coordinates. DXF uses a local metre grid, with its origin recorded in the file.</p><div class="modal-grid">'+[['backup','Editable SAMI backup'],['geojson','GeoJSON · GIS'],['dxf','DXF · CAD'],['kml','KML · mapping'],['csv','Materials CSV'],['print','Print / save PDF']].map(([k,t])=>button(t,k,k==='backup')).join('')+'</div>');$('#modalBody').onclick=e=>{const k=e.target.closest('[data-action]')?.dataset.action;if(!k)return;({backup:exportProjectJSON,geojson:exportGeoJSON,dxf:exportDXF,kml:exportKML,csv:exportCSV,print:()=>{closeModal();closeDrawer();if(state.project.area){state.mode='plan';setModeUI('plan');switchBase('drawing',false);fitArea();}requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()));}})[k]?.();};}
let toastTimer;function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000);}
let modalFocus;function showModal(title,html){modalFocus=document.activeElement;$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modalBody').onclick=null;$('#modal').classList.remove('hidden');$('#modalClose').focus();}function closeModal(){$('#modal').classList.add('hidden');modalFocus?.focus?.();}
function updateRailButton(){const c=$('#toolRail').classList.contains('collapsed');$('#railCollapse').textContent=c?'☰':'‹';$('#railCollapse').setAttribute('aria-expanded',String(!c));$('#railCollapse').setAttribute('aria-label',c?'Expand planning tools':'Collapse planning tools');}
function saveRail(){const r=$('#toolRail');setPref('sami.toolrail',JSON.stringify({left:parseFloat(r.style.left),top:parseFloat(r.style.top),collapsed:r.classList.contains('collapsed')}));}
function clampRail(){const r=$('#toolRail'),w=$('#workspace');if(!r.style.top)return;const rightReserve=68;const maxX=Math.max(7,w.clientWidth-r.offsetWidth-rightReserve),maxY=Math.max(55,w.clientHeight-r.offsetHeight-85);r.style.left=Math.max(7,Math.min(maxX,parseFloat(r.style.left)||7))+'px';r.style.top=Math.max(55,Math.min(maxY,parseFloat(r.style.top)||55))+'px';}
function initToolRail(){const r=$('#toolRail'),h=$('#railMove');let p={};try{p=JSON.parse(readPref('sami.toolrail')||'{}');}catch{}if(p.collapsed)r.classList.add('collapsed');if(Number.isFinite(p.left)&&Number.isFinite(p.top)){r.style.left=p.left+'px';r.style.top=p.top+'px';clampRail();}updateRailButton();$('#railCollapse').onclick=()=>{r.classList.toggle('collapsed');updateRailButton();clampRail();saveRail();};let drag=null;h.onpointerdown=e=>{const b=r.getBoundingClientRect();drag={dx:e.clientX-b.left,dy:e.clientY-b.top};h.setPointerCapture(e.pointerId);e.preventDefault();};h.onpointermove=e=>{if(!drag)return;const b=$('#workspace').getBoundingClientRect();r.style.left=e.clientX-b.left-drag.dx+'px';r.style.top=e.clientY-b.top-drag.dy+'px';clampRail();};const stop=e=>{if(!drag)return;drag=null;h.releasePointerCapture?.(e.pointerId);saveRail();};h.onpointerup=stop;h.onpointercancel=stop;}

const trustedSources=[
 {keys:['railway','rail line','network rail','rail boundary','rail'],org:'Network Rail',title:'Asset Protection & Optimisation — working on or near the railway',url:'https://www.networkrail.co.uk/our-work/looking-after-the-railway/asset-protection-and-optimisation/',desc:'Official Network Rail route for third-party work on or near railway infrastructure.'},
 {keys:['underground','buried service','services','excavat','digging','cable','utility'],org:'HSE',title:'HSG47 — Avoiding danger from underground services',url:'https://www.hse.gov.uk/pubns/books/hsg47.htm',desc:'HSE guidance for planning work, locating buried services and safe excavation.'},
 {keys:['overhead line','power line','ohl','electric line'],org:'HSE',title:'GS6 — Avoiding danger from overhead power lines',url:'https://www.hse.gov.uk/pubns/gs6.htm',desc:'Official HSE guidance for planning and controlling work near overhead power lines.'},
 {keys:['cdm','construction design management','principal designer','principal contractor'],org:'HSE',title:'Construction (Design and Management) Regulations 2015',url:'https://www.hse.gov.uk/construction/cdm/2015/index.htm',desc:'Official HSE CDM 2015 guidance and dutyholder information.'},
 {keys:['lifting','loler','crane','lift plan'],org:'HSE',title:'LOLER — Lifting Operations and Lifting Equipment Regulations',url:'https://www.hse.gov.uk/work-equipment-machinery/loler.htm',desc:'Official HSE information on LOLER and lifting operations.'},
 {keys:['vehicle','traffic','workplace transport','reversing','site access'],org:'HSE',title:'Workplace transport safety',url:'https://www.hse.gov.uk/workplacetransport/index.htm',desc:'Official HSE workplace transport guidance.'},
 {keys:['flood','flood zone','surface water'],org:'GOV.UK / Environment Agency',title:'Flood map for planning',url:'https://flood-map-for-planning.service.gov.uk/',desc:'Official flood risk information for planning in England.'}
];

function updateVoiceButton(){$('#muteSami').textContent=readPref('sami.voice.output')==='off'?'Voice off':'Voice on';$('#muteSami').setAttribute('aria-label',readPref('sami.voice.output')==='off'?'Enable SAMI talk-back':'Mute SAMI talk-back');}
function initVoice(){if(readPref('sami.voice.output')===null)setPref('sami.voice.output','on');if('speechSynthesis'in window){const load=()=>{state.voices=speechSynthesis.getVoices();populateVoiceSelect();};load();speechSynthesis.addEventListener('voiceschanged',load);}}
function primeSpeech(){try{window.speechSynthesis?.resume();}catch{}}
function preferredVoice(){const vs=window.speechSynthesis?.getVoices()||state.voices;return vs.find(v=>v.name===readPref('sami.voice.name'))||vs.find(v=>/^en-GB/i.test(v.lang)&&/Natural|Enhanced|Premium|Daniel|Serena|Kate|Oliver/i.test(v.name))||vs.find(v=>/^en-GB/i.test(v.lang))||vs.find(v=>/^en/i.test(v.lang));}
function populateVoiceSelect(){const sel=$('#samiVoiceSelect');if(!sel)return;const vs=window.speechSynthesis?.getVoices()||state.voices;sel.innerHTML='<option value="">Best available British English voice</option>'+vs.filter(v=>/^en/i.test(v.lang)).map(v=>'<option value="'+esc(v.name)+'">'+esc(v.name)+' · '+esc(v.lang)+'</option>').join('');sel.value=readPref('sami.voice.name')||'';}
function speakOptional(text,force=false){if(!force&&readPref('sami.voice.output')==='off')return;if(!('speechSynthesis'in window)){if(force)toast('Talk-back is unavailable in this browser.');return;}try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),v=preferredVoice();if(v)u.voice=v;u.lang=v?.lang||'en-GB';u.rate=.98;state.utterance=u;u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))toast('Speech playback was unavailable. The reply is shown on screen.');};speechSynthesis.speak(u);}catch{toast('Speech playback is unavailable.');}}
function updateAskLabel(){const active=state.listening||state.voiceStarting;$('#sendBtn').classList.toggle('listening',active);$('#sendBtn').setAttribute('aria-pressed',String(active));$('#sendBtn').setAttribute('aria-label',active?'Stop listening':$('#askInput').value.trim()?'Send typed request':'Ask SAMI by voice');$('#askButtonLabel').textContent=state.voiceStarting?'Starting…':state.listening?'Listening…':$('#askInput').value.trim()?'Send request':'Ask SAMI';$('#voiceHint').textContent=active?'Speak naturally · tap the same button to stop':'Tap Ask SAMI to speak · type and press Enter to send';}
function handleAskButton(){primeSpeech();if(state.listening||state.voiceStarting){stopVoiceCapture();return;}if($('#askInput').value.trim())sendAsk();else startVoiceCapture();}
function stopVoiceCapture(){const r=state.recognition;if(state.voiceStarting){state.recognition=null;try{r?.abort();}catch{}state.voiceStarting=false;state.listening=false;updateAskLabel();return;}try{r?.stop();}catch{}state.listening=false;updateAskLabel();}
function startVoiceCapture(){window.speechSynthesis?.cancel();const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){showModal('Ask SAMI voice','<p>This browser does not provide speech capture. Type your request, or use the microphone on your device keyboard.</p><p class="subtle">Open the hosted app in Safari or another browser that supports speech recognition. Talk-back can work independently of capture.</p>');return;}const r=new SR();state.recognition=r;state.voiceStarting=true;state.voiceResultHandled=false;state.voiceError=false;let transcript='';r.lang='en-GB';r.interimResults=true;r.continuous=false;r.maxAlternatives=1;updateAskLabel();const current=()=>state.recognition===r;
 r.onstart=()=>{if(!current()){r.abort();return;}state.voiceStarting=false;state.listening=true;updateAskLabel();};r.onresult=e=>{if(!current())return;transcript=Array.from(e.results).map(x=>x[0].transcript).join(' ').trim();$('#askInput').value=transcript;if(e.results[e.results.length-1]?.isFinal&&!state.voiceResultHandled){state.voiceResultHandled=true;try{r.stop();}catch{}sendAsk(transcript);}};r.onerror=e=>{if(!current())return;state.voiceError=true;const messages={'not-allowed':'Allow microphone and speech recognition permission for this site.','service-not-allowed':'Speech capture is not enabled by this browser.','audio-capture':'No microphone input is available.','no-speech':'No speech was heard. Tap Ask SAMI and try again.','network':'The speech service could not connect. Typed requests still work.'};if(e.error!=='aborted')toast(messages[e.error]||'Speech capture stopped. You can type your request.');};r.onend=()=>{if(!current())return;state.listening=false;state.voiceStarting=false;state.recognition=null;if(!state.voiceResultHandled&&!state.voiceError&&transcript){state.voiceResultHandled=true;sendAsk(transcript);}updateAskLabel();};try{r.start();}catch{state.recognition=null;state.listening=false;state.voiceStarting=false;updateAskLabel();toast('Microphone could not start. Check permission or type a request.');}}
function sendAsk(forced){const q=String(forced||$('#askInput').value).trim();if(!q)return;$('#askInput').value='';updateAskLabel();addMessage('user',q);$('#samiPanel').classList.add('open');handleCommand(q);}
function addMessage(who,text,source){const d=document.createElement('div');d.className='msg '+who;d.innerHTML='<p>'+esc(text)+'</p>';if(source){let url;try{url=new URL(source.url);}catch{}if(url&&url.protocol==='https:')d.innerHTML+='<a class="source-card" href="'+esc(url.href)+'" target="_blank" rel="noopener"><span>'+esc(source.org||'Source')+'</span><strong>'+esc(source.title||'Read source')+'</strong><small>'+esc(source.desc||'')+'</small></a>';}$('#samiMessages').appendChild(d);$('#samiMessages').scrollTop=$('#samiMessages').scrollHeight;}
function samiSay(text){addMessage('sami',text);speakOptional(text);}
async function handleCommand(q){const n=q.toLowerCase().trim();
 if(/^(undo|undo that|go back one)[.!]?$/.test(n)){undo();samiSay('Undo requested.');return;}if(/^redo/.test(n)){redo();samiSay('Redo requested.');return;}
 if(/unlock.*(map|plan|view)/.test(n)){setLock(false);samiSay('View unlocked.');return;}if(/lock.*(map|plan|view)/.test(n)){setLock(true);samiSay('View locked. Drawing tools remain available.');return;}
 if(/satellite/.test(n)){if(state.mode==='plan')setMode('map');switchBase('satellite');samiSay('Satellite view opened.');return;}
 if(/plan drawing|drawing view|open (the )?plan/.test(n)){if(setMode('plan'))samiSay('The shared plan area is fitted to the window.');else samiSay('Define a plan area using two opposite corners first.');return;}
 if(/define|set|create/.test(n)&&/plan area/.test(n)){openDrawer('area');samiSay('Choose two opposite corners or use the visible map area.');return;}
 if(/map view|street view/.test(n)){setMode('map');switchBase('street');samiSay('Map view opened.');return;}
 if(/open|show|add|build/.test(n)&&/panel|trakway/.test(n)){setMode('route');samiSay('Choose the panels and run width, then press Draw a Trakway route.');return;}
 if(/open|show|add/.test(n)&&/assets?|welfare|cabin/.test(n)){openDrawer('assets');samiSay('Choose a site asset, adjust its dimensions and place it.');return;}
 if(/open|show|load/.test(n)&&/services?|constraints?|utilities/.test(n)){openDrawer('services');samiSay('Choose the types to display, then draw, import or load records for your plan area.');return;}
 if(/library/.test(n)){setMode('library');samiSay('The materials and item library is open.');return;}
 if(/zoom in|zoom out/.test(n)){if(isLocked()){samiSay('Unlock the view to change the zoom.');return;}n.includes('in')?state.map.zoomIn():state.map.zoomOut();samiSay('Zoom changed.');return;}
 if(/my location|current location|where am i/.test(n)){locate();samiSay('Requesting your current location.');return;}if(/fit.*(site|plan|project)/.test(n)){fitProject();samiSay('Fit plan requested.');return;}
 if(/draw|start|create/.test(n)&&/access|egress|route|measure|area/.test(n)){const t=n.includes('access')?'access':n.includes('egress')?'egress':n.includes('measure')?'measure':n.includes('area')?'area':'route';startTool(t,{snap:t==='measure'});samiSay('Tap your points, then press Finish.');return;}
 if(/add|create|place/.test(n)&&/note/.test(n)){const text=q.replace(/^.*?note\s*/i,'').trim();if(text)startTool('note',{text,label:text});else startNote();samiSay('Tap where you want the note placed.');return;}
 if(/export/.test(n)){if(/dxf|cad/.test(n))exportDXF();else if(/geojson/.test(n))exportGeoJSON();else if(/kml/.test(n))exportKML();else if(/csv|schedule/.test(n))exportCSV();else openExport();samiSay('Your export is ready to choose or download.');return;}
 const source=trustedSources.map(s=>({s,score:s.keys.filter(k=>n.includes(k)).length})).sort((a,b)=>b.score-a.score)[0];if(source?.score){addMessage('sami','Here is a relevant official reference. Open it to check the governing guidance and project requirements.',source.s);speakOptional('I have linked the official source on screen.');return;}
 if(window.SAMI_CONFIG?.aiEndpoint){await askConnectedAI(q);return;}samiSay('Try “open panels”, “define plan area”, “satellite view”, “lock map” or “undo”. Open Help on the side to find all planning tools.');}
async function askConnectedAI(query){try{const r=await fetch(window.SAMI_CONFIG.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,project:{name:state.project.name,area:state.project.area,itemCount:state.project.features.length},policy:'official-source-grounded',allowMapActions:true}),signal:AbortSignal.timeout(20000)});const data=await boundedJSON(r,200000);if(typeof data.answer!=='string')throw Error();samiSay(data.answer.slice(0,12000));for(const s of (Array.isArray(data.sources)?data.sources:[]).slice(0,8))addMessage('sami','Source',s);const a=data.action;if(a?.type==='activateTool'&&['access','egress','route','area','measure','hazard'].includes(a.tool))startTool(a.tool);else if(a?.type==='setView'&&G.validCoord([a.lng,a.lat])){if(state.mode==='plan')setMode('map');state.map.setView([a.lat,a.lng],Math.max(3,Math.min(23,Number(a.zoom)||18)));}}catch{samiSay('The connected service did not respond. Local drawing and map commands still work.');}}
init();
})();
